services:
  db:
    image: postgres:16
    container_name: chess_postgres
    environment:
      POSTGRES_DB: chess
      POSTGRES_USER: chess
      POSTGRES_PASSWORD: chess
    ports:
      - "5432:5432"
    volumes:
      - chess_pgdata:/var/lib/postgresql/data

volumes:
  chess_pgdata:
